version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    commit_message:
      prefix: 'feat'
      prefix_development: 'chore'
      include_scope: true
    ignored_updates:
      - match:
          dependency_name: husky
          version_requirement: 5.x
